### ISSUE TITLE
ToDos

### ISSUE THREAD

**Issue by jolupa** [jolupa/stdbgames#4]
- [x] Method to Recovery Password
- [x] Dark theme for the CSS
-- It seems that Bulma.io is working on this, let's wait.
- [x] Add Stadia Exclusives and First on Stadia to Games
- [x] History of Pro prices
- [x] History if a game was Pro and When
- [x] User registration
- [x] Votes
- [ ] Finish to add genres to games as said on #12 
- [x] Work on chart for prices #8
-- problem with the new array treatment on PHP
-- trying different libraries to see if some one can work 
- [ ] Add buttons for link genres #13 more visual appealing.
- [ ] Add (badges?) To show different interactions to registered users
-- like/dislikes
-- wishlisted/library
--![20210305_204009.jpg](https://user-images.githubusercontent.com/3421696/110165862-d6405f80-7df3-11eb-8a7a-c0eb96dd4348.jpg)
- [ ] Add some kind of news to add some background to the rumours
- [ ] Add profile to users to retrieve information from Stadia to make some stats
-- Some kind of chart to see more used games on the platform.
